name: Deploy repo to Shiny Server

on: 
  push:
    branches: [staging]
  # Allow to run manually from Action tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Clone public repo to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          REPOSRC=https://github.com/CEN-Nouvelle-Aquitaine/PNA_Fadet_prospection.git
          LOCALREPO=/srv/shiny-server/annuaire-competences
          LOCALREPO_VC_DIR=$LOCALREPO/.git
          if [ ! -d $LOCALREPO_VC_DIR ]
          then
              git clone $REPOSRC $LOCALREPO
          else
              cd $LOCALREPO
              git pull $REPOSRC
          fi
